import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { ChooseAvatarStep } from '../components/steps/ChooseAvatarStep';
import { EnterCodeStep } from '../components/steps/EnterCodeStep';
import { EnterNameStep } from '../components/steps/EnterNameStep';
import { EnterPhoneStep } from '../components/steps/EnterPhoneStep';
import { GithubStep } from '../components/steps/GithubStep';
import { WelcomeStep } from '../components/steps/WelcomeStep';

const stepsComponents = {
  0: WelcomeStep,
  1: GithubStep,
  3: EnterNameStep,
  4: ChooseAvatarStep,
  5: EnterPhoneStep,
  6: EnterCodeStep,
};

type MainContextProps = {
  onNextStep: () => void;
  setUserData: React.Dispatch<React.SetStateAction<TUserData | undefined>>;
  step: number;
  userData: TUserData;
  setFieldValue: (field: keyof TUserData, value: string | number) => void;
};

export interface TUserData {
  id: string;
  fullname: string;
  avatarUrl: string;
  isActive: number;
  username: string;
  phone: string;
  token?: string;
}

export const MainContext = React.createContext<MainContextProps>({} as MainContextProps);

const Home: NextPage = () => {
  const [step, setStep] = React.useState<number>(0);
  const [userData, setUserData] = React.useState<TUserData>();
  const Step = stepsComponents[step];

  const onNextStep = () => {
    setStep((prev) => prev + 1);
  };

  const setFieldValue = (field: string, value: string | number) => {
    setUserData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  console.log(userData);

  return (
    <>
      <Head>
        <title>Clubhouse: Drop-in audio chat</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainContext.Provider value={{ step, onNextStep, setUserData, userData, setFieldValue }}>
        <Step />
      </MainContext.Provider>
    </>
  );
};

export default Home;
